"""create operational tables

Revision ID: 1ef9dfb826bb
Revises: 
Create Date: 2026-09-15 22:13:08.114665

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1ef9dfb826bb'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_request_id'), 'ai_usage', ['request_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_table('failures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('error_type', sa.String(length=128), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failures_request_id'), 'failures', ['request_id'], unique=False)
    op.create_table('request_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_request_id'), 'request_logs', ['request_id'], unique=True)
    op.create_table('workflow_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_idempotency_key'), 'workflow_executions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_workflow_executions_request_id'), 'workflow_executions', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_executions_request_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_idempotency_key'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_request_logs_request_id'), table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_index(op.f('ix_failures_request_id'), table_name='failures')
    op.drop_table('failures')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_ai_usage_request_id'), table_name='ai_usage')
    op.drop_table('ai_usage')
    # ### end Alembic commands ###
